### ISSUE TITLE
能否添加一个自动向服务器所有玩家发放邮件的功能

### ISSUE THREAD

**Issue by juanyans** [SmallJiu/Email#1]
能否添加一个自动向服务器所有玩家发放邮件的功能，最好可以定时的那种，想在局域网联机时实现类似自动发送每日奖励邮件的功能。
1.20.1

**Comment by SmallJiu** [comment]
以前的ui有点蔽塞不好塞按钮，现在改ui之后就加了，https://github.com/SmallJiu/Inbox/releases/tag/1.20.1-1.1.2-a0
