### ISSUE TITLE
1.20.1 点击邮箱图标崩溃 提示InventoryOpenEvent cannot be triggered asynchronously from another thread.

### ISSUE THREAD

**Issue by ColdTearsYY** [SmallJiu/Email#2]
Internal Exception: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
求修复谢谢
使用版本：Email-1.20.1-1.0.0.jar

**Comment by SmallJiu** [comment]
> 内部异常：java.lang.IllegalStateException：无法从另一个线程异步触发 InventoryOpenEvent。 求修复谢谢 使用版本:Email-1.20.1-1.0.0.jar

崩溃日志呢，没有的话latest.log也行

**Comment by SmallJiu** [comment]
> Internal Exception: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread. 求修复谢谢 使用版本：Email-1.20.1-1.0.0.jar

根据异常信息修复的版本，试试看是否解决，此为[下载链接](https://pan.baidu.com/s/1pmZK6zWO3C9pryweut2Y1g?pwd=aj8m)
