### ISSUE TITLE
1.12最新版本打不开

### ISSUE THREAD

**Issue by MicroNeutron** [SmallJiu/Email#3]
如题，只装一个也打不开

**Comment by SmallJiu** [comment]
> 如题，只装一个也打不开

请提供最新的崩溃日志，如果没有，请提供最新的日志

**Comment by MicroNeutron** [comment]
[crash-2024-03-12_01.10.29-server.txt](https://github.com/SmallJiu/Inbox/files/14567546/crash-2024-03-12_01.10.29-server.txt)
[错误报告-2024-03-12_上午_01.10.47.zip](https://github.com/SmallJiu/Inbox/files/14567544/-2024-03-12_._01.10.47.zip)

**Comment by SmallJiu** [comment]
> [crash-2024-03-12_01.10.29-server.txt](https://github.com/SmallJiu/Inbox/files/14567546/crash-2024-03-12_01.10.29-server.txt)
> [错误报告-2024-03-12_上午_01.10.47.zip](https://github.com/SmallJiu/Inbox/files/14567544/-2024-03-12_._01.10.47.zip)
> 

能否试着删除邮箱文件，就是saves/<存档名称>/email/<你的uuid>.json

**Comment by MicroNeutron** [comment]
应该不是存档更新的问题 新开的档也不行

**Comment by MicroNeutron** [comment]
而且a1的排版似乎有点问题，不知道是不是jei的原因（不是，试过了
还有收不到自己发的邮件（其实聊天栏收到提示了但是格子里没有）

**Comment by MicroNeutron** [comment]
![image](https://github.com/SmallJiu/Inbox/assets/90130404/2e3755bd-5b57-4603-9115-1a3b65c1db77)
额只装一个也是这样(T ^ T)

**Comment by SmallJiu** [comment]
> ![image](https://github.com/SmallJiu/Inbox/assets/90130404/2e3755bd-5b57-4603-9115-1a3b65c1db77)
> 额只装一个也是这样(T ^ T) 

这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下

**Comment by SmallJiu** [comment]
我在自己的本地客户端也复现了无法打开邮箱然后崩端的问题，初步判断为移植项目到idea时忘记配置at文件的路径，我已经编译好了一份自己测试不崩端的版本，不过此版本后续还要添加一些功能，所以暂时还不正式发布。[此为这个修复版本的链接。](https://pan.baidu.com/s/1d8nj8VGWhauocGbng3_BvA?pwd=9980)

**Comment by MicroNeutron** [comment]
> 我在自己的本地客户端也复现了无法打开邮箱然后崩端的问题，初步判断为移植项目到idea时忘记配置at文件的路径，我已经编译好了一份自己测试不崩端的版本，不过此版本后续还要添加一些功能，所以暂时还不正式发布。[此为这个修复版本的链接。](https://pan.baidu.com/s/1d8nj8VGWhauocGbng3_BvA?pwd=9980)

新版本很好用，有一点小问题：
与旧版本不兼容
没有历史发送人时点历史发送人可能会崩
回车不能换行

**Comment by MicroNeutron** [comment]
> > ![image](https://private-user-images.githubusercontent.com/90130404/312157426-2e3755bd-5b57-4603-9115-1a3b65c1db77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjkzODgsIm5iZiI6MTcxMDUyOTA4OCwicGF0aCI6Ii85MDEzMDQwNC8zMTIxNTc0MjYtMmUzNzU1YmQtNWI1Ny00NjAzLTkxMTUtMWEzYjY1YzFkYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYmI1ODUzMWM0NDk0NzI4ZjU1OGEyMzI0M2JmM2U2ZDAyYzNiOGI3YzYyODlmMmVmNjdkYWEyY2QxNTJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuBsoktQ1xoyYExyHC187J5h9DoaMYyCH25LhzePGn4)
> > 额只装一个也是这样(T ^ T)
> 
> 这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下

删配置文件确实可以恢复正常，但是如果用回a0的话，又会变成：
![image](https://github.com/SmallJiu/Inbox/assets/90130404/63569d0e-4e81-43de-89d5-67daa516099e)
（ps. 也可以通过删配置文件回复
然而这个版本还和高版本不兼容，这就导致以前的世界无法升级高版本

**Comment by SmallJiu** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/90130404/312157426-2e3755bd-5b57-4603-9115-1a3b65c1db77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjkzODgsIm5iZiI6MTcxMDUyOTA4OCwicGF0aCI6Ii85MDEzMDQwNC8zMTIxNTc0MjYtMmUzNzU1YmQtNWI1Ny00NjAzLTkxMTUtMWEzYjY1YzFkYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYmI1ODUzMWM0NDk0NzI4ZjU1OGEyMzI0M2JmM2U2ZDAyYzNiOGI3YzYyODlmMmVmNjdkYWEyY2QxNTJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuBsoktQ1xoyYExyHC187J5h9DoaMYyCH25LhzePGn4)
> > > 额只装一个也是这样(T ^ T)
> > 
> > 这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下
> 
> 删配置文件确实可以恢复正常，但是如果用回a0的话，又会变成：
> ![image](https://github.com/SmallJiu/Inbox/assets/90130404/63569d0e-4e81-43de-89d5-67daa516099e)
> （ps. 也可以通过删配置文件回复
> 然而这个版本还和高版本不兼容，这就导致以前的世界无法升级高版本
> 

这里的不兼容是指无法获取到低版本的邮箱，还是只是gui文字或图案方面的错位

**Comment by SmallJiu** [comment]
> > 我在自己的本地客户端也复现了无法打开邮箱然后崩端的问题，初步判断为移植项目到idea时忘记配置at文件的路径，我已经编译好了一份自己测试不崩端的版本，不过此版本后续还要添加一些功能，所以暂时还不正式发布。[此为这个修复版本的链接。](https://pan.baidu.com/s/1d8nj8VGWhauocGbng3_BvA?pwd=9980)
> 
> 新版本很好用，有一点小问题：
> 与旧版本不兼容
> 没有历史发送人时点历史发送人可能会崩
> 回车不能换行

会崩这个是已知问题，正式发布时会修复的，回车这个是指附加消息吗，可以使用小键盘的上下（↑↓）键选行

**Comment by MicroNeutron** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/90130404/312157426-2e3755bd-5b57-4603-9115-1a3b65c1db77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjkzODgsIm5iZiI6MTcxMDUyOTA4OCwicGF0aCI6Ii85MDEzMDQwNC8zMTIxNTc0MjYtMmUzNzU1YmQtNWI1Ny00NjAzLTkxMTUtMWEzYjY1YzFkYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYmI1ODUzMWM0NDk0NzI4ZjU1OGEyMzI0M2JmM2U2ZDAyYzNiOGI3YzYyODlmMmVmNjdkYWEyY2QxNTJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuBsoktQ1xoyYExyHC187J5h9DoaMYyCH25LhzePGn4)
> > > > 额只装一个也是这样(T ^ T)
> > > 
> > > 这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下
> > 
> > 删配置文件确实可以恢复正常，但是如果用回a0的话，又会变成：
> > ![image](https://github.com/SmallJiu/Inbox/assets/90130404/63569d0e-4e81-43de-89d5-67daa516099e)
> > （ps. 也可以通过删配置文件回复
> > 然而这个版本还和高版本不兼容，这就导致以前的世界无法升级高版本
> > 
> 
> 这里的不兼容是指无法获取到低版本的邮箱，还是只是gui文字或图案方面的错位

装过低版本或者高版本加载过的世界在切换版本进入世界的时候会崩，不过新世界仍然可以装，文字错位应该是配置文件的问题

**Comment by MicroNeutron** [comment]
> > > 我在自己的本地客户端也复现了无法打开邮箱然后崩端的问题，初步判断为移植项目到idea时忘记配置at文件的路径，我已经编译好了一份自己测试不崩端的版本，不过此版本后续还要添加一些功能，所以暂时还不正式发布。[此为这个修复版本的链接。](https://pan.baidu.com/s/1d8nj8VGWhauocGbng3_BvA?pwd=9980)
> > 
> > 新版本很好用，有一点小问题：
> > 与旧版本不兼容
> > 没有历史发送人时点历史发送人可能会崩
> > 回车不能换行
> 
> 会崩这个是已知问题，正式发布时会修复的，回车这个是指附加消息吗，可以使用小键盘的上下（↑↓）键选行

👌🏻所以说是小问题(｡>∀<｡)

**Comment by SmallJiu** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/90130404/312157426-2e3755bd-5b57-4603-9115-1a3b65c1db77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjkzODgsIm5iZiI6MTcxMDUyOTA4OCwicGF0aCI6Ii85MDEzMDQwNC8zMTIxNTc0MjYtMmUzNzU1YmQtNWI1Ny00NjAzLTkxMTUtMWEzYjY1YzFkYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYmI1ODUzMWM0NDk0NzI4ZjU1OGEyMzI0M2JmM2U2ZDAyYzNiOGI3YzYyODlmMmVmNjdkYWEyY2QxNTJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuBsoktQ1xoyYExyHC187J5h9DoaMYyCH25LhzePGn4)
> > > > > 额只装一个也是这样(T ^ T)
> > > > 
> > > > 这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下
> > > 
> > > 删配置文件确实可以恢复正常，但是如果用回a0的话，又会变成：
> > > ![image](https://github.com/SmallJiu/Inbox/assets/90130404/63569d0e-4e81-43de-89d5-67daa516099e)
> > > （ps. 也可以通过删配置文件回复
> > > 然而这个版本还和高版本不兼容，这就导致以前的世界无法升级高版本
> > > 
> > 
> > 这里的不兼容是指无法获取到低版本的邮箱，还是只是gui文字或图案方面的错位
> 
> 装过低版本或者高版本加载过的世界在切换版本进入世界的时候会崩，不过新世界仍然可以装，文字错位应该是配置文件的问题

那么能否提供下崩溃日志呢

**Comment by MicroNeutron** [comment]
> > > > > > ![image](https://private-user-images.githubusercontent.com/90130404/312157426-2e3755bd-5b57-4603-9115-1a3b65c1db77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjkzODgsIm5iZiI6MTcxMDUyOTA4OCwicGF0aCI6Ii85MDEzMDQwNC8zMTIxNTc0MjYtMmUzNzU1YmQtNWI1Ny00NjAzLTkxMTUtMWEzYjY1YzFkYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYmI1ODUzMWM0NDk0NzI4ZjU1OGEyMzI0M2JmM2U2ZDAyYzNiOGI3YzYyODlmMmVmNjdkYWEyY2QxNTJjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuBsoktQ1xoyYExyHC187J5h9DoaMYyCH25LhzePGn4)
> > > > > > 额只装一个也是这样(T ^ T)
> > > > > 
> > > > > 
> > > > > 这个可否试着把config/jiu/email/main.cfg删掉或者在可视化配置文件的gui里面恢复默认配置。如果不行的话，能否提供显示屏的大小和游戏的窗口大小，我会试着修复一下
> > > > 
> > > > 
> > > > 删配置文件确实可以恢复正常，但是如果用回a0的话，又会变成：
> > > > ![image](https://private-user-images.githubusercontent.com/90130404/313306180-63569d0e-4e81-43de-89d5-67daa516099e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzM2MzEsIm5iZiI6MTcxMDYzMzMzMSwicGF0aCI6Ii85MDEzMDQwNC8zMTMzMDYxODAtNjM1NjlkMGUtNGU4MS00M2RlLTg5ZDUtNjdkYWE1MTYwOTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIzNTUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZGI4MDY0M2UyZGY0MGFkMzQ5ZTc5YWNkOTc5N2NkZDhmZDBjNmI3NTI4ODQ2NTAwODFiNjhhOTNhMWNhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrKBv0X37JiWh2EAn7l56Ml4PNoBB5pJwbeJsCOmpqM)
> > > > （ps. 也可以通过删配置文件回复
> > > > 然而这个版本还和高版本不兼容，这就导致以前的世界无法升级高版本
> > > 
> > > 
> > > 这里的不兼容是指无法获取到低版本的邮箱，还是只是gui文字或图案方面的错位
> > 
> > 
> > 装过低版本或者高版本加载过的世界在切换版本进入世界的时候会崩，不过新世界仍然可以装，文字错位应该是配置文件的问题
> 
> 那么能否提供下崩溃日志呢

[a0转a3时发生的崩溃.zip](https://github.com/SmallJiu/Inbox/files/14625594/a0.a3.zip)
[a3转a0时发生的崩溃.zip](https://github.com/SmallJiu/Inbox/files/14625595/a3.a0.zip)

**Comment by SmallJiu** [comment]
[inbox-1.0.4-a0.jar.zip](https://github.com/SmallJiu/Inbox/files/14635524/inbox-1.0.4-a0.jar.zip)
能否使用这个版本再试下呢，由于更改了版本号，以及把一个功能加上去了，不好判断1.0.4-a0（原1.0.3-a3）的一些问题。把文件拓展名删掉.zip即可

**Comment by MicroNeutron** [comment]
[103a0至104a0的错误报告.zip](https://github.com/SmallJiu/Inbox/files/14643247/103a0.104a0.zip)

**Comment by SmallJiu** [comment]
> [103a0至104a0的错误报告.zip](https://github.com/SmallJiu/Inbox/files/14643247/103a0.104a0.zip)

已修复，发布到了mcmod上，正式版本号为1.0.4-a0
